#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <chrono>
#include <thread>
#include <future>
#include <sstream>
#include <iomanip>
#include <array>
#include <stdexcept>
#include <memory>
#include <cstdio>
#include <ncurses.h>